$(document).ready(function(){
    $(".box").hide('fastest');
    $("#cvbox").hide('fastest');
    $("#contactbox").hide('fastest');
    $("#navabout").addClass("active");
    $("#educationheader").addClass("active");

    $("#navcv").click(function(){
        $(".cvheader").removeClass("active");
    	$("#educationheader").addClass("active");
	$("#navabout").removeClass("active");
	$("#navcv").addClass("active");
	$(".box").hide();
    	$("#educationbox").show();
	$("#cvbox").fadeIn('fast');
	$("#aboutbox").fadeOut('fast');
	$("#contactbox").fadeOut('fast');
	});
    $("#navabout").click(function(){
	$("#navabout").addClass("active");
	$("#navcv").removeClass("active");
	$(".box").hide();
	$("#aboutbox").fadeIn('fast');
	$("#cvbox").fadeOut('fast');
	$("#contactbox").fadeOut('fast');
	});
    $("#navcontact").click(function(){
	$(".box").hide();
	$("#contactbox").fadeIn('fast');
	$("#aboutbox").fadeOut('fast');
	$("#cvbox").fadeOut('fast');
	});
    $("#educationbox").show();
    $("#educationheader").click(function(){
        $(".cvheader").removeClass("active");
    	$("#educationheader").addClass("active");
	$(".box").slideUp('fast');
	$("#educationbox").slideDown('fast');
	});
    $("#teachingheader").click(function(){
        $(".cvheader").removeClass("active");
    	$("#teachingheader").addClass("active");
	$(".box").slideUp('fast');
	$("#teachingbox").slideDown('fast');
	});
    $("#publicationsheader").click(function(){
        $(".cvheader").removeClass("active");
    	$("#publicationsheader").addClass("active");
	$(".box").slideUp('fast');
	$("#publicationsbox").slideDown('fast');
	});
    $("#awardsheader").click(function(){
        $(".cvheader").removeClass("active");
    	$("#awardsheader").addClass("active");
	$(".box").slideUp('fast');
	$("#awardsbox").slideDown('fast');
	});
    $("#relatedheader").click(function(){
        $(".cvheader").removeClass("active");
    	$("#relatedheader").addClass("active");
	$(".box").slideUp('fast');
	$("#relatedbox").slideDown('fast');
	});
});
